// <auto-generated />
using System;
using Fudbalski_turnir.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Fudbalski_turnir.Data.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20251207202117_AddedUtakmicaToTurnir")]
    partial class AddedUtakmicaToTurnir
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.22")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Fudbalski_turnir.Models.Klub", b =>
                {
                    b.Property<int>("KlubID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("KlubID"));

                    b.Property<int>("BrojIgraca")
                        .HasColumnType("int");

                    b.Property<int>("BrojOsvojenihTitula")
                        .HasColumnType("int");

                    b.Property<int>("GodinaOsnivanja")
                        .HasColumnType("int");

                    b.Property<string>("ImeKluba")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("RankingTima")
                        .HasColumnType("int");

                    b.Property<string>("Stadion")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("KlubID");

                    b.ToTable("Klub");
                });

            modelBuilder.Entity("Fudbalski_turnir.Models.Osoba", b =>
                {
                    b.Property<int>("OsobaID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("OsobaID"));

                    b.Property<DateTime>("DatumRodjenja")
                        .HasColumnType("datetime2");

                    b.Property<string>("Ime")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Nacionalnost")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Prezime")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime>("UKlubuDo")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("UKlubuOd")
                        .HasColumnType("datetime2");

                    b.HasKey("OsobaID");

                    b.ToTable("Osoba");

                    b.UseTptMappingStrategy();
                });

            modelBuilder.Entity("Fudbalski_turnir.Models.Sponzor", b =>
                {
                    b.Property<int>("SponzorID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("SponzorID"));

                    b.Property<string>("ImeSponzora")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("KontaktSponzora")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<decimal>("VrednostSponzora")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("SponzorID");

                    b.ToTable("Sponzor");
                });

            modelBuilder.Entity("Fudbalski_turnir.Models.Turnir", b =>
                {
                    b.Property<int>("TurnirID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("TurnirID"));

                    b.Property<DateTime>("DatumPocetka")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DatumZavrsetka")
                        .HasColumnType("datetime2");

                    b.Property<string>("Lokacija")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("NazivTurnira")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("TipTurnira")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("TurnirID");

                    b.ToTable("Turnir");
                });

            modelBuilder.Entity("Fudbalski_turnir.Models.Utakmica", b =>
                {
                    b.Property<int>("UtakmicaID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("UtakmicaID"));

                    b.Property<DateTime>("Datum")
                        .HasColumnType("datetime2");

                    b.Property<int>("DrugiKlubGolovi")
                        .HasColumnType("int");

                    b.Property<string>("DrugiKlubNaziv")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int?>("DrugiKlubPenali")
                        .HasColumnType("int");

                    b.Property<string>("Kolo")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Mesto")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<bool>("Penali")
                        .HasColumnType("bit");

                    b.Property<bool>("Produzeci")
                        .HasColumnType("bit");

                    b.Property<int>("PrviKlubGolovi")
                        .HasColumnType("int");

                    b.Property<string>("PrviKlubNaziv")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int?>("PrviKlubPenali")
                        .HasColumnType("int");

                    b.Property<int>("TipUcesca")
                        .HasColumnType("int");

                    b.Property<int?>("TurnirID")
                        .HasColumnType("int");

                    b.HasKey("UtakmicaID");

                    b.HasIndex("TurnirID");

                    b.ToTable("Utakmica");
                });

            modelBuilder.Entity("KlubTurnir", b =>
                {
                    b.Property<int>("KluboviKlubID")
                        .HasColumnType("int");

                    b.Property<int>("TurnirID")
                        .HasColumnType("int");

                    b.HasKey("KluboviKlubID", "TurnirID");

                    b.HasIndex("TurnirID");

                    b.ToTable("Ucestvuje", (string)null);
                });

            modelBuilder.Entity("KlubUtakmica", b =>
                {
                    b.Property<int>("KluboviKlubID")
                        .HasColumnType("int");

                    b.Property<int>("UtakmiceUtakmicaID")
                        .HasColumnType("int");

                    b.HasKey("KluboviKlubID", "UtakmiceUtakmicaID");

                    b.HasIndex("UtakmiceUtakmicaID");

                    b.ToTable("Igra", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("AspNetUsers", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("ProviderKey")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("RoleId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("LoginProvider")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("Name")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("SponzorTurnir", b =>
                {
                    b.Property<int>("SponzorID")
                        .HasColumnType("int");

                    b.Property<int>("TurnirID")
                        .HasColumnType("int");

                    b.HasKey("SponzorID", "TurnirID");

                    b.HasIndex("TurnirID");

                    b.ToTable("Sponzorise", (string)null);
                });

            modelBuilder.Entity("Fudbalski_turnir.Models.Igrac", b =>
                {
                    b.HasBaseType("Fudbalski_turnir.Models.Osoba");

                    b.Property<int>("BrojDresa")
                        .HasColumnType("int");

                    b.Property<int>("KlubID")
                        .HasColumnType("int");

                    b.Property<string>("Pozicija")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.ToTable("Igraci");
                });

            modelBuilder.Entity("Fudbalski_turnir.Models.Menadzer", b =>
                {
                    b.HasBaseType("Fudbalski_turnir.Models.Osoba");

                    b.Property<int>("GodineIskustva")
                        .HasColumnType("int");

                    b.Property<int>("KlubID")
                        .HasColumnType("int");

                    b.ToTable("Menadzeri");
                });

            modelBuilder.Entity("Fudbalski_turnir.Models.Utakmica", b =>
                {
                    b.HasOne("Fudbalski_turnir.Models.Turnir", "Turnir")
                        .WithMany("Utakmice")
                        .HasForeignKey("TurnirID");

                    b.Navigation("Turnir");
                });

            modelBuilder.Entity("KlubTurnir", b =>
                {
                    b.HasOne("Fudbalski_turnir.Models.Klub", null)
                        .WithMany()
                        .HasForeignKey("KluboviKlubID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Fudbalski_turnir.Models.Turnir", null)
                        .WithMany()
                        .HasForeignKey("TurnirID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("KlubUtakmica", b =>
                {
                    b.HasOne("Fudbalski_turnir.Models.Klub", null)
                        .WithMany()
                        .HasForeignKey("KluboviKlubID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Fudbalski_turnir.Models.Utakmica", null)
                        .WithMany()
                        .HasForeignKey("UtakmiceUtakmicaID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("SponzorTurnir", b =>
                {
                    b.HasOne("Fudbalski_turnir.Models.Sponzor", null)
                        .WithMany()
                        .HasForeignKey("SponzorID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Fudbalski_turnir.Models.Turnir", null)
                        .WithMany()
                        .HasForeignKey("TurnirID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Fudbalski_turnir.Models.Igrac", b =>
                {
                    b.HasOne("Fudbalski_turnir.Models.Osoba", null)
                        .WithOne()
                        .HasForeignKey("Fudbalski_turnir.Models.Igrac", "OsobaID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Fudbalski_turnir.Models.Menadzer", b =>
                {
                    b.HasOne("Fudbalski_turnir.Models.Osoba", null)
                        .WithOne()
                        .HasForeignKey("Fudbalski_turnir.Models.Menadzer", "OsobaID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Fudbalski_turnir.Models.Turnir", b =>
                {
                    b.Navigation("Utakmice");
                });
#pragma warning restore 612, 618
        }
    }
}
