// <auto-generated />
using System;
using FudbalskiTurnir.DAL;
using FudbalskiTurnir.DAL.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace FudbalskiTurnir.DAL.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20251205154838_SeperateTables")]
    partial class SeperateTables : Migration
    {
        protected override void Up(MigrationBuilder migrationBuilder)
        {
            // your migration Up code here
        }

        protected override void Down(MigrationBuilder migrationBuilder)
        {
            // your migration Down code here
        }

        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.22")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("FudbalskiTurnir.DAL.Models.Klub", b =>
            {
                b.Property<int>("KlubID").ValueGeneratedOnAdd().HasColumnType("int");
                SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("KlubID"));
                b.Property<int>("BrojIgraca").HasColumnType("int");
                b.Property<int>("BrojOsvojenihTitula").HasColumnType("int");
                b.Property<int>("GodinaOsnivanja").HasColumnType("int");
                b.Property<string>("ImeKluba").IsRequired().HasColumnType("nvarchar(max)");
                b.Property<int>("RankingTima").HasColumnType("int");
                b.Property<string>("Stadion").IsRequired().HasColumnType("nvarchar(max)");
                b.HasKey("KlubID");
                b.ToTable("Klub");
            });

            modelBuilder.Entity("FudbalskiTurnir.DAL.Models.Osoba", b =>
            {
                b.Property<int>("OsobaID").ValueGeneratedOnAdd().HasColumnType("int");
                SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("OsobaID"));
                b.Property<DateTime>("DatumRodjenja").HasColumnType("datetime2");
                b.Property<string>("Ime").IsRequired().HasColumnType("nvarchar(max)");
                b.Property<string>("Nacionalnost").IsRequired().HasColumnType("nvarchar(max)");
                b.Property<string>("Prezime").IsRequired().HasColumnType("nvarchar(max)");
                b.Property<DateTime>("UKlubuDo").HasColumnType("datetime2");
                b.Property<DateTime>("UKlubuOd").HasColumnType("datetime2");
                b.HasKey("OsobaID");
                b.ToTable("Osoba");
                b.UseTptMappingStrategy();
            });

            modelBuilder.Entity("FudbalskiTurnir.DAL.Models.Sponzor", b =>
            {
                b.Property<int>("SponzorID").ValueGeneratedOnAdd().HasColumnType("int");
                SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("SponzorID"));
                b.Property<string>("ImeSponzora").IsRequired().HasColumnType("nvarchar(max)");
                b.Property<string>("KontaktSponzora").IsRequired().HasColumnType("nvarchar(max)");
                b.Property<decimal>("VrednostSponzora").HasColumnType("decimal(18,2)");
                b.HasKey("SponzorID");
                b.ToTable("Sponzor");
            });

            modelBuilder.Entity("FudbalskiTurnir.DAL.Models.Turnir", b =>
            {
                b.Property<int>("TurnirID").ValueGeneratedOnAdd().HasColumnType("int");
                SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("TurnirID"));
                b.Property<DateTime>("DatumPocetka").HasColumnType("datetime2");
                b.Property<DateTime>("DatumZavrsetka").HasColumnType("datetime2");
                b.Property<string>("Lokacija").IsRequired().HasColumnType("nvarchar(max)");
                b.Property<string>("NazivTurnira").IsRequired().HasColumnType("nvarchar(max)");
                b.Property<string>("TipTurnira").IsRequired().HasColumnType("nvarchar(max)");
                b.HasKey("TurnirID");
                b.ToTable("Turnir");
            });

            modelBuilder.Entity("FudbalskiTurnir.DAL.Models.Utakmica", b =>
            {
                b.Property<int>("UtakmicaID").ValueGeneratedOnAdd().HasColumnType("int");
                SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("UtakmicaID"));
                b.Property<DateTime>("Datum").HasColumnType("datetime2");
                b.Property<int>("DrugiKlubGolovi").HasColumnType("int");
                b.Property<string>("DrugiKlubNaziv").IsRequired().HasColumnType("nvarchar(max)");
                b.Property<int>("DrugiKlubPenali").HasColumnType("int");
                b.Property<string>("Kolo").IsRequired().HasColumnType("nvarchar(max)");
                b.Property<string>("Mesto").IsRequired().HasColumnType("nvarchar(max)");
                b.Property<bool>("Penali").HasColumnType("bit");
                b.Property<bool>("Produzeci").HasColumnType("bit");
                b.Property<int>("PrviKlubGolovi").HasColumnType("int");
                b.Property<string>("PrviKlubNaziv").IsRequired().HasColumnType("nvarchar(max)");
                b.Property<int>("PrviKlubPenali").HasColumnType("int");
                b.Property<int>("TipUcesca").HasColumnType("int");
                b.HasKey("UtakmicaID");
                b.ToTable("Utakmica");
            });

#pragma warning restore 612, 618
        }
    }
}
